name: Artifacts

on:
    workflow_dispatch:

env:
    build-artifact-key: app-${{ github.sha }}
    test-coverage-key: test-coverage-${{ github.sha }}

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: app
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '23.x'
          - name: Download dependencies
            uses: actions/cache@v3
            id: cache
            with:
                path: app/node_modules
                key: deps-node-moduels-${{ hashFiles('app/package-lock.json') }}
          - name: Install dependencies
            if: steps.cache.outputs.cache-hit != 'true'
            run: npm ci
          - name: Unit tests
            run: npm run test -- --coverage
          - name: Upload test results
            uses: actions/upload-artifact@v3
            with:
                name: ${{ env.test-coverage-key }}
                path: app/coverage
          - name: Build code
            run: npm run build
          - name: Upload build files
            uses: actions/upload-artifact@v4
            with:
              name: ${{ env.build-artifact-key }}
              path: app/build
    deploy:
        runs-on: ubuntu-latest
        needs: test-build
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                name: ${{ env.build-artifact-key }}
                path: build
            - name: Show folder structure
              run: ls -R
