# This workflow is triggered manually and contains two jobs: echo-hello and echo-goodbye.
# The echo-hello job runs first and prints "Hello, World!" to the console.
# The echo-goodbye job runs second and contains a step that always succeeds,
# followed by a step that prints "Goodbye, World!" to the console.


name: Building Blocks

on: workflow_dispatch

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, World!"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Successful step
              run: | 
                echo "I am a successful step"
                exit 0
            - name: Say Goodbye
              run: echo "Goodbye, World!"
