# This workflow demostrates the use of expressions in GitHub Actions.
# It includes a workflow dispatch input to enable or disable debug mode.
# It also includes conditional steps that run based on the value of the debug input and the branch from which the workflow is triggered.
# The workflow is triggered on push events and can be manually triggered using the workflow dispatch event.
# The workflow includes steps to print start-up data and a greeting message.

name: Expressions
run-name: Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF'}}

on: 
    workflow_dispatch:
        inputs:
            debug:
                description: 'Enable debug mode'
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print start-up data'
              if: inputs.debug
              run: |
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}"
            - name: '[debug] Print when triggered from main'
              if: inputs.debug && github.ref == 'refs/heads/main'
              run: echo "I was triggered from the main branch"
            - name: Gretting
              run: echo "Hello, world!"
    
