# This workflow demonstrates the use of event filters and activity types in GitHub Actions.
# It triggers on pull_request events with specific activity types and branches.
# The workflow includes a job that runs on the specified events and prints a message.

name: Event Filters and Activity Types

on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This job runs on pull_request events with types 'opened' and 'synchronized' for the main branch."