# This workflow demonstrates the use of functions in GitHub Actions.
# It includes conditional steps based on the pull request title and labels.
# It also shows how to use the 'cancelled()' function to check if the workflow was cancelled.
# The workflow is triggered on pull request events.
# The workflow includes steps to print the pull request title and labels,
# as well as steps that will execute or skip based on the success or failure of previous steps.
# The workflow also includes a step that will execute if the workflow is cancelled.

name: Functions

on: 
    pull_request:

jobs: 
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Print PR title
              run: echo ${{ github.event.pull_request.title }}
            - name: Print PR labels
              run: | 
                cat << EOF 
                ${{ toJSON(github.event.pull_request.labels) }}
                EOF
            - name: Bug step
              if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
              run: echo "I am a bug fix"
            - name: Sleep for 20 seconds
              run: sleep 20
            - name: Failing step
              run: exit 1
            - name: I will be skipped
              if: ${{ success() }}
              run: echo "I will print if the previous step was successful"
            - name: I will be executed
              if: ${{ failure() }}
              run: echo "I will print if any previous step failed"
            - name: I will be execute
              if: ${{ !cancelled() }}
              run: echo "I will always print, except when the workflow is cancelled"
            - name: I will execute when cancelled
              if: ${{ cancelled() }}
              run: echo "I will print if the workflow is cancelled"
