name: Functions

on: 
    pull_request:
    workflow_dispatch:

jobs: 
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Failing step
              run: exit 1
            - name: I will be skipped
              if: ${{ success() }}
              run: echo "I will print if the previous step was successful"
            - name: I will be executed
              if: ${{ failure() }}
              run: echo "I will print if any previous step failed"
            - name: I will be execute
              if: ${{ !cancelled() }}
              run: echo "I will always print, except when the workflow is cancelled"
            - name: I will execute when cancelled
              if: ${{ cancelled() }}
              run: echo "I will print if the workflow is cancelled"




