name: Matrices

on: 
    workflow_dispatch:

jobs:
    backwards-compatibility:
        name: ${{ matrix.os }} - ${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [21.x, 22.x, 23.x]
                os: 
                    - ubuntu-latest
                    - windows-latest
                include:
                  - os: ubuntu-latest
                    node-version: 21.x
                  - os: ubuntu-latest
                    node-version: 23.x
                    tag: experimental
        steps:
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{ matrix.node-version }}
            - name: Fail if experimental
              if: ${{ matrix.tag == 'experimental' }}
              run: exit 1
            - name: Perform some tests
              run: |
               echo "Running tests on OS ${{ matrix.os }} and Node.js ${{ matrix.node-version }}"
               sleep 10
            - name: Upload test results
              run: echo "Uploading test results"
