# This workflow demonstrates how to use the 'github.event_name' context
# to get the name of the event that triggered the workflow.
# It runs on pull_request and workflow_dispatch events.
# The workflow will echo the event name to the console.
# The workflow is triggered by pull_request and workflow_dispatch events.

name: Workflow Events

on:
    pull_request:
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the event name
              run: |
                echo "The event name is: ${{ github.event_name }} ."