name: Workflow Events

on:
    pull_request:
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the event name
              run: |
                echo "The event name is: ${{ github.event_name }} ."